name: CI
on: [push]
jobs:
  test:
    name: Lint, and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install deps - root (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: client

      - name: Install deps - client (with cache)
        uses: bahmutov/npm-install@v1
      - name: Build client
        run: yarn build
        working-directory: client

      - name: Lint
        run: yarn lint

      - name: Test and publish coverage to codeclimate
        uses: paambaati/codeclimate-action@v3.0.0
        with:
          coverageCommand: yarn test
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install deps - root (with cache)
        uses: bahmutov/npm-install@v1

      - name: Install deps and build - client (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: client
      - name: Build client
        run: yarn build
        working-directory: client

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
